provinces = [
    {"id": 3, "name": "تهران"},
    {"id": 4, "name": "البرز"},
    {"id": 5, "name": "خراسان رضوی"},
    {"id": 7, "name": "آذربایجان شرقی"},
    {"id": 8, "name": "آذربایجان غربی"},
    {"id": 9, "name": "اردبیل"},
    {"id": 10, "name": "اصفهان"},
    {"id": 11, "name": "ایلام"},
    {"id": 12, "name": "بوشهر"},
    {"id": 13, "name": "چهارمحال و بختیاری"},
    {"id": 14, "name": "خراسان جنوبی"},
    {"id": 15, "name": "خراسان شمالی"},
    {"id": 16, "name": "خوزستان"},
    {"id": 17, "name": "زنجان"},
    {"id": 18, "name": "سمنان"},
    {"id": 19, "name": "سیستان و بلوچستان"},
    {"id": 20, "name": "فارس"},
    {"id": 21, "name": "قزوین"},
    {"id": 22, "name": "قم"},
    {"id": 23, "name": "کردستان"},
    {"id": 24, "name": "کرمان"},
    {"id": 25, "name": "کرمانشاه"},
    {"id": 26, "name": "کهگیلویه وبویراحمد"},
    {"id": 27, "name": "گلستان"},
    {"id": 28, "name": "گیلان"},
    {"id": 29, "name": "لرستان"},
    {"id": 30, "name": "مازندران"},
    {"id": 31, "name": "مرکزی"},
    {"id": 32, "name": "هرمزگان"},
    {"id": 33, "name": "همدان"},
    {"id": 34, "name": "یزد"},
]

cities = [
    {"id": 2, "name": "تهران", "province_id": 3},
    {"id": 3, "name": "کرج", "province_id": 4},
    {"id": 4, "name": "مشهد", "province_id": 5},
    {"id": 5, "name": "فردیس", "province_id": 4},
    {"id": 6, "name": "کمال‌شهر", "province_id": 4},
    {"id": 7, "name": "نظرآباد", "province_id": 4},
    {"id": 8, "name": "محمدشهر", "province_id": 4},
    {"id": 9, "name": "ماهدشت", "province_id": 4},
    {"id": 10, "name": "مشکین‌دشت", "province_id": 4},
    {"id": 11, "name": "هشتگرد", "province_id": 4},
    {"id": 12, "name": "چهارباغ", "province_id": 4},
    {"id": 13, "name": "شهر جدید هشتگرد", "province_id": 4},
    {"id": 14, "name": "اشتهارد", "province_id": 4},
    {"id": 15, "name": "گرمدره", "province_id": 4},
    {"id": 16, "name": "گلسار", "province_id": 4},
    {"id": 17, "name": "کوهسار", "province_id": 4},
    {"id": 18, "name": "تنکمان", "province_id": 4},
    {"id": 19, "name": "طالقان", "province_id": 4},
    {"id": 20, "name": "آسارا", "province_id": 4},
    {"id": 21, "name": "اسلام‌شهر", "province_id": 3},
    {"id": 22, "name": "شهریار", "province_id": 3},
    {"id": 23, "name": "قدس", "province_id": 3},
    {"id": 24, "name": "ملارد", "province_id": 3},
    {"id": 25, "name": "صالحیه", "province_id": 3},
    {"id": 26, "name": "پاکدشت", "province_id": 3},
    {"id": 27, "name": "قرچک", "province_id": 3},
    {"id": 28, "name": "ورامین", "province_id": 3},
    {"id": 29, "name": "گلستان", "province_id": 3},
    {"id": 30, "name": "ری", "province_id": 3},
    {"id": 31, "name": "اندیشه", "province_id": 3},
    {"id": 32, "name": "رباط کریم", "province_id": 3},
    {"id": 33, "name": "پرند", "province_id": 3},
    {"id": 34, "name": "باغستان", "province_id": 3},
    {"id": 35, "name": "پردیس", "province_id": 3},
    {"id": 36, "name": "بومهن", "province_id": 3},
    {"id": 37, "name": "باقرشهر", "province_id": 3},
    {"id": 38, "name": "پیشوا", "province_id": 3},
    {"id": 39, "name": "نسیم شهر", "province_id": 3},
    {"id": 40, "name": "صباشهر", "province_id": 3},
    {"id": 41, "name": "چهاردانگه", "province_id": 3},
    {"id": 42, "name": "دماوند", "province_id": 3},
    {"id": 43, "name": "حسن آباد", "province_id": 3},
    {"id": 44, "name": "وحیدیه", "province_id": 3},
    {"id": 45, "name": "نصیرشهر", "province_id": 3},
    {"id": 46, "name": "فردوسیه", "province_id": 3},
    {"id": 47, "name": "رودهن", "province_id": 3},
    {"id": 48, "name": "شاهدشهر", "province_id": 3},
    {"id": 49, "name": "صفادشت", "province_id": 3},
    {"id": 50, "name": "فیروزکوه", "province_id": 3},
    {"id": 51, "name": "لواسان", "province_id": 3},
    {"id": 52, "name": "آبسرد", "province_id": 3},
    {"id": 53, "name": "شریف آباد", "province_id": 3},
    {"id": 54, "name": "کهریزک", "province_id": 3},
    {"id": 55, "name": "فشم", "province_id": 3},
    {"id": 56, "name": "جوادآباد", "province_id": 3},
    {"id": 57, "name": "فرون آباد", "province_id": 3},
    {"id": 58, "name": "آبعلی", "province_id": 3},
    {"id": 59, "name": "کیلان", "province_id": 3},
    {"id": 60, "name": "شمشک", "province_id": 3},
    {"id": 61, "name": "احمدآباد مستوفی", "province_id": 3},
    {"id": 62, "name": "ارجمند", "province_id": 3},
    {"id": 64, "name": "شهر ری", "province_id": 3},
    {"id": 65, "name": "تبریز", "province_id": 7},
    {"id": 66, "name": "رشت", "province_id": 28},
    {"id": 67, "name": "شیراز", "province_id": 20},
    {"id": 68, "name": "قزوین", "province_id": 21},
    {"id": 69, "name": "اصفهان", "province_id": 10},
    {"id": 70, "name": "ساوجبلاغ", "province_id": 4},
    {"id": 71, "name": "قم", "province_id": 22},
    {"id": 72, "name": "آمل", "province_id": 30},
    {"id": 73, "name": "یزد", "province_id": 34},
    {"id": 74, "name": "اهواز", "province_id": 16},
    {"id": 75, "name": "ساری", "province_id": 30},
    {"id": 76, "name": "ارومیه", "province_id": 8},
    {"id": 77, "name": "سیرجان", "province_id": 24},
    {"id": 78, "name": "بندرعباس", "province_id": 32},
]

vendors = [
    {"id": 1, "name": "vendor 1", "is_active": True},
    {"id": 2, "name": "vendor 2", "is_active": False},
    {"id": 3, "name": "vendor 3", "is_active": False},
    {"id": 4, "name": "vendor 4", "is_active": False},
    {"id": 5, "name": "vendor 5", "is_active": False},
    {"id": 6, "name": "vendor 6", "is_active": False},
    {"id": 7, "name": "vendor 7", "is_active": False},
    {"id": 8, "name": "vendor 8", "is_active": False},
    {"id": 9, "name": "vendor 9", "is_active": False},
    {"id": 10, "name": "vendor 10", "is_active": False},
    {"id": 11, "name": "vendor 11", "is_active": False},
    {"id": 12, "name": "vendor 12", "is_active": False},
    {"id": 13, "name": "vendor 13", "is_active": False},
    {"id": 14, "name": "vendor 14", "is_active": False},
    {"id": 15, "name": "vendor 15", "is_active": False},
    {"id": 16, "name": "vendor 16", "is_active": False},
    {"id": 17, "name": "vendor 17", "is_active": False},
    {"id": 18, "name": "vendor 18", "is_active": False},
    {"id": 19, "name": "vendor 19", "is_active": False},
    {"id": 20, "name": "vendor 20", "is_active": False},
    {"id": 21, "name": "vendor 21", "is_active": False},
    {"id": 22, "name": "vendor 22", "is_active": False},
    {"id": 23, "name": "vendor 23", "is_active": False},
    {"id": 24, "name": "vendor 24", "is_active": False},
    {"id": 25, "name": "vendor 25", "is_active": False},
    {"id": 26, "name": "vendor 26", "is_active": False},
    {"id": 27, "name": "vendor 27", "is_active": False},
    {"id": 28, "name": "vendor 28", "is_active": False},
    {"id": 29, "name": "vendor 29", "is_active": False},
    {"id": 30, "name": "vendor 30", "is_active": False},
    {"id": 31, "name": "vendor 31", "is_active": False},
    {"id": 32, "name": "vendor 32", "is_active": False},
    {"id": 33, "name": "vendor 33", "is_active": False},
    {"id": 34, "name": "vendor 34", "is_active": False},
    {"id": 35, "name": "vendor 35", "is_active": False},
    {"id": 36, "name": "vendor 36", "is_active": False},
    {"id": 37, "name": "vendor 37", "is_active": False},
    {"id": 38, "name": "vendor 38", "is_active": False},
    {"id": 39, "name": "vendor 39", "is_active": False},
    {"id": 40, "name": "vendor 40", "is_active": False},
    {"id": 41, "name": "vendor 41", "is_active": False},
    {"id": 42, "name": "vendor 42", "is_active": False},
    {"id": 43, "name": "vendor 43", "is_active": False},
    {"id": 44, "name": "vendor 44", "is_active": False},
    {"id": 45, "name": "vendor 45", "is_active": False},
    {"id": 46, "name": "vendor 46", "is_active": False},
    {"id": 47, "name": "vendor 47", "is_active": False},
    {"id": 48, "name": "vendor 48", "is_active": False},
    {"id": 49, "name": "vendor 49", "is_active": False},
    {"id": 50, "name": "vendor 50", "is_active": False},
    {"id": 51, "name": "vendor 51", "is_active": False},
    {"id": 52, "name": "vendor 52", "is_active": False},
    {"id": 53, "name": "vendor 53", "is_active": False},
    {"id": 54, "name": "vendor 54", "is_active": False},
    {"id": 55, "name": "vendor 55", "is_active": False},
    {"id": 56, "name": "vendor 56", "is_active": False},
    {"id": 57, "name": "vendor 57", "is_active": False},
    {"id": 58, "name": "vendor 58", "is_active": False},
    {"id": 59, "name": "vendor 59", "is_active": False},
    {"id": 60, "name": "vendor 60", "is_active": False},
    {"id": 61, "name": "vendor 61", "is_active": False},
    {"id": 62, "name": "vendor 62", "is_active": False},
    {"id": 63, "name": "vendor 63", "is_active": False},
    {"id": 64, "name": "vendor 64", "is_active": False},
    {"id": 65, "name": "vendor 65", "is_active": False},
    {"id": 66, "name": "vendor 66", "is_active": False},
    {"id": 67, "name": "vendor 67", "is_active": False},
    {"id": 68, "name": "vendor 68", "is_active": False},
    {"id": 69, "name": "vendor 69", "is_active": False},
    {"id": 70, "name": "vendor 70", "is_active": False},
    {"id": 71, "name": "vendor 71", "is_active": False},
    {"id": 72, "name": "vendor 72", "is_active": False},
    {"id": 73, "name": "vendor 73", "is_active": False},
    {"id": 74, "name": "vendor 74", "is_active": False},
    {"id": 75, "name": "vendor 75", "is_active": False},
    {"id": 76, "name": "vendor 76", "is_active": False},
    {"id": 77, "name": "vendor 77", "is_active": False},
    {"id": 78, "name": "vendor 78", "is_active": False},
    {"id": 79, "name": "vendor 79", "is_active": False},
    {"id": 80, "name": "vendor 80", "is_active": False},
    {"id": 81, "name": "vendor 81", "is_active": False},
    {"id": 82, "name": "vendor 82", "is_active": False},
    {"id": 83, "name": "vendor 83", "is_active": False},
    {"id": 84, "name": "vendor 84", "is_active": False},
    {"id": 85, "name": "vendor 85", "is_active": False},
    {"id": 86, "name": "vendor 86", "is_active": False},
    {"id": 87, "name": "vendor 87", "is_active": False},
    {"id": 88, "name": "vendor 88", "is_active": False},
    {"id": 89, "name": "vendor 89", "is_active": False},
    {"id": 90, "name": "vendor 80", "is_active": False},
    {"id": 91, "name": "vendor 91", "is_active": False},
    {"id": 92, "name": "vendor 92", "is_active": False},
    {"id": 93, "name": "vendor 93", "is_active": False},
    {"id": 94, "name": "vendor 94", "is_active": False},
    {"id": 95, "name": "vendor 95", "is_active": False},
    {"id": 96, "name": "vendor 96", "is_active": False},
    {"id": 97, "name": "vendor 97", "is_active": False},
    {"id": 98, "name": "vendor 98", "is_active": False},
    {"id": 99, "name": "vendor 99", "is_active": False},
    {"id": 100, "name": "vendor 100", "is_active": False},
]

vendor_informations = [
    {
        "id": 1,
        "vendor_id": 1,
        "city_id": 2,
        "address": "آدرس متنی اول",
        "number_of_unique_products": 20,
        "mean_daily_sales": 50,
        "hygiene_score": 10,
        "created_at": "2023-02-11 13:42:20",
    },
]

vendor_information_evaluations = [
    {
        "id": 1,
        "vendor_information_id": 1,
        "status": "accepted",
        "created_at": "2023-02-11 13:43:10",
        "updated_at": "2023-02-12 10:32:20",
    },
]


vendor_selections = [
    {
        "id": 1,
        "vendor_information_evaluation_id": 1,
        "status": "accepted",
        "created_at": "2023-02-12 13:45:00",
        "updated_at": "2023-02-15 11:25:20",
    },
]

contracts = [
    {
        "id": 1,
        "vendor_id": 1,
        "created_at": "2023-02-20 15:12:00",
    }
]
