provinces = [
    {"id": 3, "name": "تهران"},
    {"id": 4, "name": "البرز"},
    {"id": 5, "name": "خراسان رضوی"},
    {"id": 7, "name": "آذربایجان شرقی"},
    {"id": 8, "name": "آذربایجان غربی"},
    {"id": 9, "name": "اردبیل"},
    {"id": 10, "name": "اصفهان"},
    {"id": 11, "name": "ایلام"},
    {"id": 12, "name": "بوشهر"},
    {"id": 13, "name": "چهارمحال و بختیاری"},
    {"id": 14, "name": "خراسان جنوبی"},
    {"id": 15, "name": "خراسان شمالی"},
    {"id": 16, "name": "خوزستان"},
    {"id": 17, "name": "زنجان"},
    {"id": 18, "name": "سمنان"},
    {"id": 19, "name": "سیستان و بلوچستان"},
    {"id": 20, "name": "فارس"},
    {"id": 21, "name": "قزوین"},
    {"id": 22, "name": "قم"},
    {"id": 23, "name": "کردستان"},
    {"id": 24, "name": "کرمان"},
    {"id": 25, "name": "کرمانشاه"},
    {"id": 26, "name": "کهگیلویه وبویراحمد"},
    {"id": 27, "name": "گلستان"},
    {"id": 28, "name": "گیلان"},
    {"id": 29, "name": "لرستان"},
    {"id": 30, "name": "مازندران"},
    {"id": 31, "name": "مرکزی"},
    {"id": 32, "name": "هرمزگان"},
    {"id": 33, "name": "همدان"},
    {"id": 34, "name": "یزد"},
]

cities = [
    {"id": 2, "name": "تهران", "province_id": 3},
    {"id": 3, "name": "کرج", "province_id": 4},
    {"id": 4, "name": "مشهد", "province_id": 5},
    {"id": 5, "name": "فردیس", "province_id": 4},
    {"id": 6, "name": "کمال‌شهر", "province_id": 4},
    {"id": 7, "name": "نظرآباد", "province_id": 4},
    {"id": 8, "name": "محمدشهر", "province_id": 4},
    {"id": 9, "name": "ماهدشت", "province_id": 4},
    {"id": 10, "name": "مشکین‌دشت", "province_id": 4},
    {"id": 11, "name": "هشتگرد", "province_id": 4},
    {"id": 12, "name": "چهارباغ", "province_id": 4},
    {"id": 13, "name": "شهر جدید هشتگرد", "province_id": 4},
    {"id": 14, "name": "اشتهارد", "province_id": 4},
    {"id": 15, "name": "گرمدره", "province_id": 4},
    {"id": 16, "name": "گلسار", "province_id": 4},
    {"id": 17, "name": "کوهسار", "province_id": 4},
    {"id": 18, "name": "تنکمان", "province_id": 4},
    {"id": 19, "name": "طالقان", "province_id": 4},
    {"id": 20, "name": "آسارا", "province_id": 4},
    {"id": 21, "name": "اسلام‌شهر", "province_id": 3},
    {"id": 22, "name": "شهریار", "province_id": 3},
    {"id": 23, "name": "قدس", "province_id": 3},
    {"id": 24, "name": "ملارد", "province_id": 3},
    {"id": 25, "name": "صالحیه", "province_id": 3},
    {"id": 26, "name": "پاکدشت", "province_id": 3},
    {"id": 27, "name": "قرچک", "province_id": 3},
    {"id": 28, "name": "ورامین", "province_id": 3},
    {"id": 29, "name": "گلستان", "province_id": 3},
    {"id": 30, "name": "ری", "province_id": 3},
    {"id": 31, "name": "اندیشه", "province_id": 3},
    {"id": 32, "name": "رباط کریم", "province_id": 3},
    {"id": 33, "name": "پرند", "province_id": 3},
    {"id": 34, "name": "باغستان", "province_id": 3},
    {"id": 35, "name": "پردیس", "province_id": 3},
    {"id": 36, "name": "بومهن", "province_id": 3},
    {"id": 37, "name": "باقرشهر", "province_id": 3},
    {"id": 38, "name": "پیشوا", "province_id": 3},
    {"id": 39, "name": "نسیم شهر", "province_id": 3},
    {"id": 40, "name": "صباشهر", "province_id": 3},
    {"id": 41, "name": "چهاردانگه", "province_id": 3},
    {"id": 42, "name": "دماوند", "province_id": 3},
    {"id": 43, "name": "حسن آباد", "province_id": 3},
    {"id": 44, "name": "وحیدیه", "province_id": 3},
    {"id": 45, "name": "نصیرشهر", "province_id": 3},
    {"id": 46, "name": "فردوسیه", "province_id": 3},
    {"id": 47, "name": "رودهن", "province_id": 3},
    {"id": 48, "name": "شاهدشهر", "province_id": 3},
    {"id": 49, "name": "صفادشت", "province_id": 3},
    {"id": 50, "name": "فیروزکوه", "province_id": 3},
    {"id": 51, "name": "لواسان", "province_id": 3},
    {"id": 52, "name": "آبسرد", "province_id": 3},
    {"id": 53, "name": "شریف آباد", "province_id": 3},
    {"id": 54, "name": "کهریزک", "province_id": 3},
    {"id": 55, "name": "فشم", "province_id": 3},
    {"id": 56, "name": "جوادآباد", "province_id": 3},
    {"id": 57, "name": "فرون آباد", "province_id": 3},
    {"id": 58, "name": "آبعلی", "province_id": 3},
    {"id": 59, "name": "کیلان", "province_id": 3},
    {"id": 60, "name": "شمشک", "province_id": 3},
    {"id": 61, "name": "احمدآباد مستوفی", "province_id": 3},
    {"id": 62, "name": "ارجمند", "province_id": 3},
    {"id": 64, "name": "شهر ری", "province_id": 3},
    {"id": 65, "name": "تبریز", "province_id": 7},
    {"id": 66, "name": "رشت", "province_id": 28},
    {"id": 67, "name": "شیراز", "province_id": 20},
    {"id": 68, "name": "قزوین", "province_id": 21},
    {"id": 69, "name": "اصفهان", "province_id": 10},
    {"id": 70, "name": "ساوجبلاغ", "province_id": 4},
    {"id": 71, "name": "قم", "province_id": 22},
    {"id": 72, "name": "آمل", "province_id": 30},
    {"id": 73, "name": "یزد", "province_id": 34},
    {"id": 74, "name": "اهواز", "province_id": 16},
    {"id": 75, "name": "ساری", "province_id": 30},
    {"id": 76, "name": "ارومیه", "province_id": 8},
    {"id": 77, "name": "سیرجان", "province_id": 24},
    {"id": 78, "name": "بندرعباس", "province_id": 32},
]

vendors = [
    {"id": 1, "name": "فروشنده اول", "is_active": True},
    {"id": 2, "name": "فروشنده دوم", "is_active": False},
]

vendor_informations = [
    {
        "id": 1,
        "vendor_id": 1,
        "city_id": 2,
        "address": "آدرس متنی اول",
        "number_of_unique_products": 20,
        "mean_daily_sales": 50,
        "hygiene_score": 10,
        "created_at": "2023-02-15 13:42:20",
    },
]

vendor_information_evaluations = [
    {
        "id": 1,
        "vendor_information_id": 1,
        "status": "rejected",
        "created_at": "2023-02-4 01:42:20",
        "updated_at": "2023-02-11 01:42:20",
    },
]
