provinces = [
    {"id": 3, "name": "تهران"},
    {"id": 4, "name": "البرز"},
    {"id": 5, "name": "خراسان رضوی"},
    {"id": 7, "name": "آذربایجان شرقی"},
    {"id": 8, "name": "آذربایجان غربی"},
    {"id": 9, "name": "اردبیل"},
    {"id": 10, "name": "اصفهان"},
    {"id": 11, "name": "ایلام"},
    {"id": 12, "name": "بوشهر"},
    {"id": 13, "name": "چهارمحال و بختیاری"},
    {"id": 14, "name": "خراسان جنوبی"},
    {"id": 15, "name": "خراسان شمالی"},
    {"id": 16, "name": "خوزستان"},
    {"id": 17, "name": "زنجان"},
    {"id": 18, "name": "سمنان"},
    {"id": 19, "name": "سیستان و بلوچستان"},
    {"id": 20, "name": "فارس"},
    {"id": 21, "name": "قزوین"},
    {"id": 22, "name": "قم"},
    {"id": 23, "name": "کردستان"},
    {"id": 24, "name": "کرمان"},
    {"id": 25, "name": "کرمانشاه"},
    {"id": 26, "name": "کهگیلویه وبویراحمد"},
    {"id": 27, "name": "گلستان"},
    {"id": 28, "name": "گیلان"},
    {"id": 29, "name": "لرستان"},
    {"id": 30, "name": "مازندران"},
    {"id": 31, "name": "مرکزی"},
    {"id": 32, "name": "هرمزگان"},
    {"id": 33, "name": "همدان"},
    {"id": 34, "name": "یزد"},
]

cities = [
    {"id": 2, "name": "تهران", "province_id": 3},
    {"id": 3, "name": "کرج", "province_id": 4},
    {"id": 4, "name": "مشهد", "province_id": 5},
    {"id": 5, "name": "فردیس", "province_id": 4},
    {"id": 6, "name": "کمال‌شهر", "province_id": 4},
    {"id": 7, "name": "نظرآباد", "province_id": 4},
    {"id": 8, "name": "محمدشهر", "province_id": 4},
    {"id": 9, "name": "ماهدشت", "province_id": 4},
    {"id": 10, "name": "مشکین‌دشت", "province_id": 4},
    {"id": 11, "name": "هشتگرد", "province_id": 4},
    {"id": 12, "name": "چهارباغ", "province_id": 4},
    {"id": 13, "name": "شهر جدید هشتگرد", "province_id": 4},
    {"id": 14, "name": "اشتهارد", "province_id": 4},
    {"id": 15, "name": "گرمدره", "province_id": 4},
    {"id": 16, "name": "گلسار", "province_id": 4},
    {"id": 17, "name": "کوهسار", "province_id": 4},
    {"id": 18, "name": "تنکمان", "province_id": 4},
    {"id": 19, "name": "طالقان", "province_id": 4},
    {"id": 20, "name": "آسارا", "province_id": 4},
    {"id": 21, "name": "اسلام‌شهر", "province_id": 3},
    {"id": 22, "name": "شهریار", "province_id": 3},
    {"id": 23, "name": "قدس", "province_id": 3},
    {"id": 24, "name": "ملارد", "province_id": 3},
    {"id": 25, "name": "صالحیه", "province_id": 3},
    {"id": 26, "name": "پاکدشت", "province_id": 3},
    {"id": 27, "name": "قرچک", "province_id": 3},
    {"id": 28, "name": "ورامین", "province_id": 3},
    {"id": 29, "name": "گلستان", "province_id": 3},
    {"id": 30, "name": "ری", "province_id": 3},
    {"id": 31, "name": "اندیشه", "province_id": 3},
    {"id": 32, "name": "رباط کریم", "province_id": 3},
    {"id": 33, "name": "پرند", "province_id": 3},
    {"id": 34, "name": "باغستان", "province_id": 3},
    {"id": 35, "name": "پردیس", "province_id": 3},
    {"id": 36, "name": "بومهن", "province_id": 3},
    {"id": 37, "name": "باقرشهر", "province_id": 3},
    {"id": 38, "name": "پیشوا", "province_id": 3},
    {"id": 39, "name": "نسیم شهر", "province_id": 3},
    {"id": 40, "name": "صباشهر", "province_id": 3},
    {"id": 41, "name": "چهاردانگه", "province_id": 3},
    {"id": 42, "name": "دماوند", "province_id": 3},
    {"id": 43, "name": "حسن آباد", "province_id": 3},
    {"id": 44, "name": "وحیدیه", "province_id": 3},
    {"id": 45, "name": "نصیرشهر", "province_id": 3},
    {"id": 46, "name": "فردوسیه", "province_id": 3},
    {"id": 47, "name": "رودهن", "province_id": 3},
    {"id": 48, "name": "شاهدشهر", "province_id": 3},
    {"id": 49, "name": "صفادشت", "province_id": 3},
    {"id": 50, "name": "فیروزکوه", "province_id": 3},
    {"id": 51, "name": "لواسان", "province_id": 3},
    {"id": 52, "name": "آبسرد", "province_id": 3},
    {"id": 53, "name": "شریف آباد", "province_id": 3},
    {"id": 54, "name": "کهریزک", "province_id": 3},
    {"id": 55, "name": "فشم", "province_id": 3},
    {"id": 56, "name": "جوادآباد", "province_id": 3},
    {"id": 57, "name": "فرون آباد", "province_id": 3},
    {"id": 58, "name": "آبعلی", "province_id": 3},
    {"id": 59, "name": "کیلان", "province_id": 3},
    {"id": 60, "name": "شمشک", "province_id": 3},
    {"id": 61, "name": "احمدآباد مستوفی", "province_id": 3},
    {"id": 62, "name": "ارجمند", "province_id": 3},
    {"id": 64, "name": "شهر ری", "province_id": 3},
    {"id": 65, "name": "تبریز", "province_id": 7},
    {"id": 66, "name": "رشت", "province_id": 28},
    {"id": 67, "name": "شیراز", "province_id": 20},
    {"id": 68, "name": "قزوین", "province_id": 21},
    {"id": 69, "name": "اصفهان", "province_id": 10},
    {"id": 70, "name": "ساوجبلاغ", "province_id": 4},
    {"id": 71, "name": "قم", "province_id": 22},
    {"id": 72, "name": "آمل", "province_id": 30},
    {"id": 73, "name": "یزد", "province_id": 34},
    {"id": 74, "name": "اهواز", "province_id": 16},
    {"id": 75, "name": "ساری", "province_id": 30},
    {"id": 76, "name": "ارومیه", "province_id": 8},
    {"id": 77, "name": "سیرجان", "province_id": 24},
    {"id": 78, "name": "بندرعباس", "province_id": 32},
]

vendors = [
    {"id": 1, "name": "vendor 1", "is_active": True},
    {"id": 2, "name": "vendor 2", "is_active": False},
    {"id": 3, "name": "vendor 3", "is_active": False},
    {"id": 4, "name": "vendor 4", "is_active": False},
    {"id": 5, "name": "vendor 5", "is_active": False},
    {"id": 6, "name": "vendor 6", "is_active": False},
    {"id": 7, "name": "vendor 7", "is_active": False},
    {"id": 8, "name": "vendor 8", "is_active": False},
    {"id": 9, "name": "vendor 9", "is_active": False},
    {"id": 10, "name": "vendor 10", "is_active": False},
    {"id": 11, "name": "vendor 11", "is_active": False},
    {"id": 12, "name": "vendor 12", "is_active": False},
    {"id": 13, "name": "vendor 13", "is_active": False},
    {"id": 14, "name": "vendor 14", "is_active": False},
    {"id": 15, "name": "vendor 15", "is_active": False},
    {"id": 16, "name": "vendor 16", "is_active": False},
    {"id": 17, "name": "vendor 17", "is_active": False},
    {"id": 18, "name": "vendor 18", "is_active": False},
    {"id": 19, "name": "vendor 19", "is_active": False},
    {"id": 20, "name": "vendor 20", "is_active": False},
    {"id": 21, "name": "vendor 21", "is_active": False},
    {"id": 22, "name": "vendor 22", "is_active": False},
    {"id": 23, "name": "vendor 23", "is_active": False},
    {"id": 24, "name": "vendor 24", "is_active": False},
    {"id": 25, "name": "vendor 25", "is_active": False},
    {"id": 26, "name": "vendor 26", "is_active": False},
    {"id": 27, "name": "vendor 27", "is_active": False},
    {"id": 28, "name": "vendor 28", "is_active": False},
    {"id": 29, "name": "vendor 29", "is_active": False},
    {"id": 30, "name": "vendor 30", "is_active": False},
    {"id": 31, "name": "vendor 31", "is_active": False},
    {"id": 32, "name": "vendor 32", "is_active": False},
    {"id": 33, "name": "vendor 33", "is_active": False},
    {"id": 34, "name": "vendor 34", "is_active": False},
    {"id": 35, "name": "vendor 35", "is_active": False},
    {"id": 36, "name": "vendor 36", "is_active": False},
    {"id": 37, "name": "vendor 37", "is_active": False},
    {"id": 38, "name": "vendor 38", "is_active": False},
    {"id": 39, "name": "vendor 39", "is_active": False},
    {"id": 40, "name": "vendor 40", "is_active": False},
    {"id": 41, "name": "vendor 41", "is_active": False},
    {"id": 42, "name": "vendor 42", "is_active": False},
    {"id": 43, "name": "vendor 43", "is_active": False},
    {"id": 44, "name": "vendor 44", "is_active": False},
    {"id": 45, "name": "vendor 45", "is_active": False},
    {"id": 46, "name": "vendor 46", "is_active": False},
    {"id": 47, "name": "vendor 47", "is_active": False},
    {"id": 48, "name": "vendor 48", "is_active": False},
    {"id": 49, "name": "vendor 49", "is_active": False},
    {"id": 50, "name": "vendor 50", "is_active": False},
    {"id": 51, "name": "vendor 51", "is_active": False},
    {"id": 52, "name": "vendor 52", "is_active": False},
    {"id": 53, "name": "vendor 53", "is_active": False},
    {"id": 54, "name": "vendor 54", "is_active": False},
    {"id": 55, "name": "vendor 55", "is_active": False},
    {"id": 56, "name": "vendor 56", "is_active": False},
    {"id": 57, "name": "vendor 57", "is_active": False},
    {"id": 58, "name": "vendor 58", "is_active": False},
    {"id": 59, "name": "vendor 59", "is_active": False},
    {"id": 60, "name": "vendor 60", "is_active": False},
    {"id": 61, "name": "vendor 61", "is_active": False},
    {"id": 62, "name": "vendor 62", "is_active": False},
    {"id": 63, "name": "vendor 63", "is_active": False},
    {"id": 64, "name": "vendor 64", "is_active": False},
    {"id": 65, "name": "vendor 65", "is_active": False},
    {"id": 66, "name": "vendor 66", "is_active": False},
    {"id": 67, "name": "vendor 67", "is_active": False},
    {"id": 68, "name": "vendor 68", "is_active": False},
    {"id": 69, "name": "vendor 69", "is_active": False},
    {"id": 70, "name": "vendor 70", "is_active": False},
    {"id": 71, "name": "vendor 71", "is_active": False},
    {"id": 72, "name": "vendor 72", "is_active": False},
    {"id": 73, "name": "vendor 73", "is_active": False},
    {"id": 74, "name": "vendor 74", "is_active": False},
    {"id": 75, "name": "vendor 75", "is_active": False},
    {"id": 76, "name": "vendor 76", "is_active": False},
    {"id": 77, "name": "vendor 77", "is_active": False},
    {"id": 78, "name": "vendor 78", "is_active": False},
    {"id": 79, "name": "vendor 79", "is_active": False},
    {"id": 80, "name": "vendor 80", "is_active": False},
    {"id": 81, "name": "vendor 81", "is_active": False},
    {"id": 82, "name": "vendor 82", "is_active": False},
    {"id": 83, "name": "vendor 83", "is_active": False},
    {"id": 84, "name": "vendor 84", "is_active": False},
    {"id": 85, "name": "vendor 85", "is_active": False},
    {"id": 86, "name": "vendor 86", "is_active": False},
    {"id": 87, "name": "vendor 87", "is_active": False},
    {"id": 88, "name": "vendor 88", "is_active": False},
    {"id": 89, "name": "vendor 89", "is_active": False},
    {"id": 90, "name": "vendor 80", "is_active": False},
    {"id": 91, "name": "vendor 91", "is_active": False},
    {"id": 92, "name": "vendor 92", "is_active": False},
    {"id": 93, "name": "vendor 93", "is_active": False},
    {"id": 94, "name": "vendor 94", "is_active": False},
    {"id": 95, "name": "vendor 95", "is_active": False},
    {"id": 96, "name": "vendor 96", "is_active": False},
    {"id": 97, "name": "vendor 97", "is_active": False},
    {"id": 98, "name": "vendor 98", "is_active": False},
    {"id": 99, "name": "vendor 99", "is_active": False},
    {"id": 100, "name": "vendor 100", "is_active": False},
]


vendor_informations = [
    {
        "id": 1,
        "vendor_id": 1,
        "city_id": 2,
        "address": "آدرس متنی",
        "number_of_unique_products": 20,
        "mean_daily_sales": 50,
        "hygiene_score": 8,
        "created_at": "2023-02-11 13:42:20",
    },
    {
        "id": 2,
        "vendor_id": 2,
        "city_id": 2,
        "address": "آدرس متنی",
        "number_of_unique_products": 20,
        "mean_daily_sales": 50,
        "hygiene_score": 7,
        "created_at": "2023-02-10 15:42:10",
    },
    {
        "id": 3,
        "vendor_id": 3,
        "city_id": 2,
        "address": "آدرس متنی",
        "number_of_unique_products": 20,
        "mean_daily_sales": 50,
        "hygiene_score": 7,
        "created_at": "2023-02-10 16:42:10",
    },
    {
        "id": 4,
        "vendor_id": 4,
        "city_id": 56,
        "address": "آدرس متنی",
        "number_of_unique_products": 21,
        "mean_daily_sales": 15,
        "hygiene_score": 3,
        "created_at": "2019-05-10 10:34:23",
    },
    {
        "id": 5,
        "vendor_id": 5,
        "city_id": 2,
        "address": "آدرس متنی",
        "number_of_unique_products": 20,
        "mean_daily_sales": 50,
        "hygiene_score": 7,
        "created_at": "2023-02-10 16:42:10",
    },
    {
        "id": 9,
        "vendor_id": 9,
        "city_id": 22,
        "address": "آدرس متنی",
        "number_of_unique_products": 164,
        "mean_daily_sales": 58,
        "hygiene_score": 3,
        "created_at": "2022-04-30 06:38:29",
    },
    {
        "id": 10,
        "vendor_id": 10,
        "city_id": 64,
        "address": "آدرس متنی",
        "number_of_unique_products": 101,
        "mean_daily_sales": 84,
        "hygiene_score": 3,
        "created_at": "2019-09-17 08:04:22",
    },
    {
        "id": 11,
        "vendor_id": 11,
        "city_id": 58,
        "address": "آدرس متنی",
        "number_of_unique_products": 79,
        "mean_daily_sales": 18,
        "hygiene_score": 7,
        "created_at": "2015-11-01 05:11:48",
    },
    {
        "id": 12,
        "vendor_id": 12,
        "city_id": 31,
        "address": "آدرس متنی",
        "number_of_unique_products": 129,
        "mean_daily_sales": 59,
        "hygiene_score": 0,
        "created_at": "2016-12-05 12:09:01",
    },
    {
        "id": 13,
        "vendor_id": 13,
        "city_id": 41,
        "address": "آدرس متنی",
        "number_of_unique_products": 23,
        "mean_daily_sales": 29,
        "hygiene_score": 3,
        "created_at": "2020-08-16 05:55:35",
    },
    {
        "id": 14,
        "vendor_id": 14,
        "city_id": 20,
        "address": "آدرس متنی",
        "number_of_unique_products": 81,
        "mean_daily_sales": 68,
        "hygiene_score": 0,
        "created_at": "2018-09-22 01:49:25",
    },
    {
        "id": 15,
        "vendor_id": 15,
        "city_id": 46,
        "address": "آدرس متنی",
        "number_of_unique_products": 107,
        "mean_daily_sales": 43,
        "hygiene_score": 3,
        "created_at": "2016-02-09 06:58:30",
    },
    {
        "id": 16,
        "vendor_id": 16,
        "city_id": 21,
        "address": "آدرس متنی",
        "number_of_unique_products": 51,
        "mean_daily_sales": 14,
        "hygiene_score": 8,
        "created_at": "2019-11-04 12:10:40",
    },
    {
        "id": 17,
        "vendor_id": 17,
        "city_id": 23,
        "address": "آدرس متنی",
        "number_of_unique_products": 149,
        "mean_daily_sales": 88,
        "hygiene_score": 9,
        "created_at": "2022-03-15 02:49:50",
    },
    {
        "id": 18,
        "vendor_id": 18,
        "city_id": 51,
        "address": "آدرس متنی",
        "number_of_unique_products": 196,
        "mean_daily_sales": 37,
        "hygiene_score": 10,
        "created_at": "2022-07-03 07:30:19",
    },
    {
        "id": 19,
        "vendor_id": 19,
        "city_id": 24,
        "address": "آدرس متنی",
        "number_of_unique_products": 150,
        "mean_daily_sales": 55,
        "hygiene_score": 2,
        "created_at": "2015-08-22 05:39:52",
    },
    {
        "id": 20,
        "vendor_id": 20,
        "city_id": 9,
        "address": "آدرس متنی",
        "number_of_unique_products": 117,
        "mean_daily_sales": 24,
        "hygiene_score": 5,
        "created_at": "2018-09-12 03:38:44",
    },
    {
        "id": 21,
        "vendor_id": 21,
        "city_id": 42,
        "address": "آدرس متنی",
        "number_of_unique_products": 130,
        "mean_daily_sales": 17,
        "hygiene_score": 0,
        "created_at": "2016-10-23 02:14:58",
    },
    {
        "id": 22,
        "vendor_id": 22,
        "city_id": 40,
        "address": "آدرس متنی",
        "number_of_unique_products": 21,
        "mean_daily_sales": 25,
        "hygiene_score": 2,
        "created_at": "2019-12-18 06:45:02",
    },
    {
        "id": 23,
        "vendor_id": 23,
        "city_id": 59,
        "address": "آدرس متنی",
        "number_of_unique_products": 150,
        "mean_daily_sales": 12,
        "hygiene_score": 1,
        "created_at": "2020-07-01 05:30:20",
    },
    {
        "id": 24,
        "vendor_id": 24,
        "city_id": 50,
        "address": "آدرس متنی",
        "number_of_unique_products": 120,
        "mean_daily_sales": 42,
        "hygiene_score": 4,
        "created_at": "2020-07-01 05:30:20",
    },
    {
        "id": 26,
        "vendor_id": 26,
        "city_id": 62,
        "address": "آدرس متنی",
        "number_of_unique_products": 183,
        "mean_daily_sales": 76,
        "hygiene_score": 2,
        "created_at": "2021-03-29 12:45:12",
    },
    {
        "id": 28,
        "vendor_id": 28,
        "city_id": 37,
        "address": "آدرس متنی",
        "number_of_unique_products": 118,
        "mean_daily_sales": 14,
        "hygiene_score": 10,
        "created_at": "2018-12-01 10:20:12",
    },
    {
        "id": 29,
        "vendor_id": 29,
        "city_id": 13,
        "address": "آدرس متنی",
        "number_of_unique_products": 124,
        "mean_daily_sales": 49,
        "hygiene_score": 8,
        "created_at": "2018-03-17 03:37:26",
    },
    {
        "id": 30,
        "vendor_id": 30,
        "city_id": 36,
        "address": "آدرس متنی",
        "number_of_unique_products": 78,
        "mean_daily_sales": 36,
        "hygiene_score": 10,
        "created_at": "2019-05-11 08:30:06",
    },
    {
        "id": 31,
        "vendor_id": 31,
        "city_id": 57,
        "address": "آدرس متنی",
        "number_of_unique_products": 22,
        "mean_daily_sales": 13,
        "hygiene_score": 1,
        "created_at": "2017-08-11 01:51:11",
    },
    {
        "id": 32,
        "vendor_id": 32,
        "city_id": 10,
        "address": "آدرس متنی",
        "number_of_unique_products": 171,
        "mean_daily_sales": 39,
        "hygiene_score": 8,
        "created_at": "2015-02-19 06:06:58",
    },
    {
        "id": 33,
        "vendor_id": 33,
        "city_id": 68,
        "address": "آدرس متنی",
        "number_of_unique_products": 149,
        "mean_daily_sales": 78,
        "hygiene_score": 7,
        "created_at": "2017-09-12 02:24:12",
    },
    {
        "id": 34,
        "vendor_id": 34,
        "city_id": 68,
        "address": "آدرس متنی",
        "number_of_unique_products": 149,
        "mean_daily_sales": 78,
        "hygiene_score": 7,
        "created_at": "2017-09-10 02:24:12",
    },
    {
        "id": 35,
        "vendor_id": 35,
        "city_id": 7,
        "address": "آدرس متنی",
        "number_of_unique_products": 3,
        "mean_daily_sales": 68,
        "hygiene_score": 1,
        "created_at": "2023-10-13 03:06:59",
    },
    {
        "id": 36,
        "vendor_id": 36,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2019-05-01 05:16:12",
    },
    {
        "id": 37,
        "vendor_id": 37,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2019-04-01 05:16:12",
    },
    {
        "id": 38,
        "vendor_id": 38,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2019-03-01 05:16:12",
    },
    {
        "id": 39,
        "vendor_id": 39,
        "city_id": 10,
        "address": "آدرس متنی",
        "number_of_unique_products": 151,
        "mean_daily_sales": 99,
        "hygiene_score": 5,
        "created_at": "2020-03-17 11:32:47",
    },
    {
        "id": 40,
        "vendor_id": 40,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2021-03-01 13:16:12",
    },
    {
        "id": 41,
        "vendor_id": 41,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2021-03-01 15:16:12",
    },
    {
        "id": 42,
        "vendor_id": 42,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2020-03-07 15:16:12",
    },
    {
        "id": 43,
        "vendor_id": 43,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2021-03-09 17:10:12",
    },
    {
        "id": 44,
        "vendor_id": 44,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2021-03-07 12:10:12",
    },
    {
        "id": 45,
        "vendor_id": 45,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2020-03-03 17:10:12",
    },
    {
        "id": 46,
        "vendor_id": 46,
        "city_id": 54,
        "address": "آدرس متنی",
        "number_of_unique_products": 50,
        "mean_daily_sales": 53,
        "hygiene_score": 3,
        "created_at": "2021-03-06 15:10:12",
    },
    {
        "id": 47,
        "vendor_id": 47,
        "city_id": 67,
        "address": "آدرس متنی",
        "number_of_unique_products": 62,
        "mean_daily_sales": 75,
        "hygiene_score": 5,
        "created_at": "2016-10-03 01:26:48",
    },
    {
        "id": 48,
        "vendor_id": 48,
        "city_id": 10,
        "address": "آدرس متنی",
        "number_of_unique_products": 151,
        "mean_daily_sales": 99,
        "hygiene_score": 5,
        "created_at": "2019-03-17 11:32:47",
    },
    {
        "id": 49,
        "vendor_id": 49,
        "city_id": 53,
        "address": "آدرس متنی",
        "number_of_unique_products": 91,
        "mean_daily_sales": 56,
        "hygiene_score": 10,
        "created_at": "2016-02-20 12:39:18",
    },
    {
        "id": 50,
        "vendor_id": 50,
        "city_id": 74,
        "address": "آدرس متنی",
        "number_of_unique_products": 174,
        "mean_daily_sales": 94,
        "hygiene_score": 0,
        "created_at": "2016-01-16 01:03:15",
    },
    {
        "id": 51,
        "vendor_id": 51,
        "city_id": 60,
        "address": "آدرس متنی",
        "number_of_unique_products": 71,
        "mean_daily_sales": 63,
        "hygiene_score": 5,
        "created_at": "2019-08-13 05:59:13",
    },
    {
        "id": 52,
        "vendor_id": 52,
        "city_id": 18,
        "address": "آدرس متنی",
        "number_of_unique_products": 141,
        "mean_daily_sales": 73,
        "hygiene_score": 9,
        "created_at": "2023-09-11 01:22:47",
    },
    {
        "id": 53,
        "vendor_id": 53,
        "city_id": 30,
        "address": "آدرس متنی",
        "number_of_unique_products": 117,
        "mean_daily_sales": 13,
        "hygiene_score": 4,
        "created_at": "2015-12-04 10:59:38",
    },
    {
        "id": 54,
        "vendor_id": 54,
        "city_id": 30,
        "address": "آدرس متنی",
        "number_of_unique_products": 117,
        "mean_daily_sales": 13,
        "hygiene_score": 4,
        "created_at": "2019-12-04 10:59:38",
    },
    {
        "id": 55,
        "vendor_id": 55,
        "city_id": 45,
        "address": "آدرس متنی",
        "number_of_unique_products": 95,
        "mean_daily_sales": 49,
        "hygiene_score": 6,
        "created_at": "2023-01-16 11:16:07",
    },
    {
        "id": 56,
        "vendor_id": 56,
        "city_id": 14,
        "address": "آدرس متنی",
        "number_of_unique_products": 85,
        "mean_daily_sales": 91,
        "hygiene_score": 0,
        "created_at": "2014-03-15 06:40:12",
    },
    {
        "id": 57,
        "vendor_id": 57,
        "city_id": 14,
        "address": "آدرس متنی",
        "number_of_unique_products": 85,
        "mean_daily_sales": 91,
        "hygiene_score": 0,
        "created_at": "2017-03-15 06:40:12",
    },
    {
        "id": 58,
        "vendor_id": 58,
        "city_id": 28,
        "address": "آدرس متنی",
        "number_of_unique_products": 91,
        "mean_daily_sales": 29,
        "hygiene_score": 8,
        "created_at": "2018-01-12 09:56:43",
    },
    {
        "id": 59,
        "vendor_id": 59,
        "city_id": 16,
        "address": "آدرس متنی",
        "number_of_unique_products": 2,
        "mean_daily_sales": 93,
        "hygiene_score": 9,
        "created_at": "2021-08-28 04:21:34",
    },
    {
        "id": 60,
        "vendor_id": 60,
        "city_id": 29,
        "address": "آدرس متنی",
        "number_of_unique_products": 26,
        "mean_daily_sales": 71,
        "hygiene_score": 0,
        "created_at": "2021-09-27 11:27:29",
    },
    {
        "id": 61,
        "vendor_id": 61,
        "city_id": 8,
        "address": "آدرس متنی",
        "number_of_unique_products": 12,
        "mean_daily_sales": 10,
        "hygiene_score": 8,
        "created_at": "2020-12-28 01:54:49",
    },
    {
        "id": 62,
        "vendor_id": 62,
        "city_id": 4,
        "address": "آدرس متنی",
        "number_of_unique_products": 68,
        "mean_daily_sales": 97,
        "hygiene_score": 2,
        "created_at": "2021-05-02 19:55:22",
    },
    {
        "id": 63,
        "vendor_id": 63,
        "city_id": 39,
        "address": "آدرس متنی",
        "number_of_unique_products": 64,
        "mean_daily_sales": 62,
        "hygiene_score": 9,
        "created_at": "2019-05-03 15:59:59",
    },
    {
        "id": 64,
        "vendor_id": 64,
        "city_id": 39,
        "address": "آدرس متنی",
        "number_of_unique_products": 64,
        "mean_daily_sales": 62,
        "hygiene_score": 9,
        "created_at": "2019-07-03 15:59:59",
    },
    {
        "id": 65,
        "vendor_id": 65,
        "city_id": 78,
        "address": "آدرس متنی",
        "number_of_unique_products": 5,
        "mean_daily_sales": 29,
        "hygiene_score": 4,
        "created_at": "2022-02-22 08:17:31",
    },
    {
        "id": 66,
        "vendor_id": 66,
        "city_id": 78,
        "address": "آدرس متنی",
        "number_of_unique_products": 5,
        "mean_daily_sales": 29,
        "hygiene_score": 4,
        "created_at": "2021-02-22 18:17:31",
    },
    {
        "id": 67,
        "vendor_id": 67,
        "city_id": 57,
        "address": "آدرس متنی",
        "number_of_unique_products": 151,
        "mean_daily_sales": 78,
        "hygiene_score": 0,
        "created_at": "2016-11-04 08:51:27",
    },
    {
        "id": 68,
        "vendor_id": 68,
        "city_id": 10,
        "address": "آدرس متنی",
        "number_of_unique_products": 112,
        "mean_daily_sales": 18,
        "hygiene_score": 1,
        "created_at": "2016-08-10 19:14:48",
    },
    {
        "id": 69,
        "vendor_id": 69,
        "city_id": 20,
        "address": "آدرس متنی",
        "number_of_unique_products": 162,
        "mean_daily_sales": 74,
        "hygiene_score": 7,
        "created_at": "2022-02-13 12:04:58",
    },
    {
        "id": 70,
        "vendor_id": 70,
        "city_id": 9,
        "address": "آدرس متنی",
        "number_of_unique_products": 106,
        "mean_daily_sales": 66,
        "hygiene_score": 8,
        "created_at": "2021-11-25 12:42:20",
    },
    {
        "id": 71,
        "vendor_id": 71,
        "city_id": 27,
        "address": "آدرس متنی",
        "number_of_unique_products": 76,
        "mean_daily_sales": 64,
        "hygiene_score": 9,
        "created_at": "2022-01-21 04:20:55",
    },
    {
        "id": 72,
        "vendor_id": 72,
        "city_id": 28,
        "address": "آدرس متنی",
        "number_of_unique_products": 181,
        "mean_daily_sales": 32,
        "hygiene_score": 8,
        "created_at": "2014-12-18 12:27:01",
    },
    {
        "id": 73,
        "vendor_id": 73,
        "city_id": 36,
        "address": "آدرس متنی",
        "number_of_unique_products": 55,
        "mean_daily_sales": 65,
        "hygiene_score": 6,
        "created_at": "2016-09-02 05:33:27",
    },
    {
        "id": 74,
        "vendor_id": 74,
        "city_id": 34,
        "address": "آدرس متنی",
        "number_of_unique_products": 175,
        "mean_daily_sales": 59,
        "hygiene_score": 0,
        "created_at": "2022-06-21 10:39:59",
    },
    {
        "id": 75,
        "vendor_id": 75,
        "city_id": 43,
        "address": "آدرس متنی",
        "number_of_unique_products": 35,
        "mean_daily_sales": 25,
        "hygiene_score": 8,
        "created_at": "2019-01-28 09:07:49",
    },
    {
        "id": 76,
        "vendor_id": 76,
        "city_id": 60,
        "address": "آدرس متنی",
        "number_of_unique_products": 158,
        "mean_daily_sales": 66,
        "hygiene_score": 4,
        "created_at": "2018-11-03 10:56:13",
    },
    {
        "id": 77,
        "vendor_id": 77,
        "city_id": 22,
        "address": "آدرس متنی",
        "number_of_unique_products": 39,
        "mean_daily_sales": 74,
        "hygiene_score": 5,
        "created_at": "2017-07-25 07:31:07",
    },
    {
        "id": 78,
        "vendor_id": 78,
        "city_id": 60,
        "address": "آدرس متنی",
        "number_of_unique_products": 158,
        "mean_daily_sales": 66,
        "hygiene_score": 4,
        "created_at": "2018-11-04 14:56:13",
    },
    {
        "id": 79,
        "vendor_id": 79,
        "city_id": 22,
        "address": "آدرس متنی",
        "number_of_unique_products": 39,
        "mean_daily_sales": 74,
        "hygiene_score": 5,
        "created_at": "2019-07-25 17:31:07",
    },
    {
        "id": 80,
        "vendor_id": 80,
        "city_id": 13,
        "address": "آدرس متنی",
        "number_of_unique_products": 157,
        "mean_daily_sales": 42,
        "hygiene_score": 5,
        "created_at": "2017-07-10 03:29:56",
    },
    {
        "id": 81,
        "vendor_id": 81,
        "city_id": 13,
        "address": "آدرس متنی",
        "number_of_unique_products": 157,
        "mean_daily_sales": 42,
        "hygiene_score": 5,
        "created_at": "2017-07-14 13:29:56",
    },
    {
        "id": 82,
        "vendor_id": 82,
        "city_id": 66,
        "address": "آدرس متنی",
        "number_of_unique_products": 33,
        "mean_daily_sales": 39,
        "hygiene_score": 3,
        "created_at": "2015-03-01 08:47:15",
    },
    {
        "id": 83,
        "vendor_id": 83,
        "city_id": 48,
        "address": "آدرس متنی",
        "number_of_unique_products": 113,
        "mean_daily_sales": 15,
        "hygiene_score": 6,
        "created_at": "2021-06-21 07:49:00",
    },
    {
        "id": 84,
        "vendor_id": 84,
        "city_id": 48,
        "address": "آدرس متنی",
        "number_of_unique_products": 113,
        "mean_daily_sales": 15,
        "hygiene_score": 6,
        "created_at": "2021-06-11 17:49:00",
    },
    {
        "id": 85,
        "vendor_id": 85,
        "city_id": 45,
        "address": "آدرس متنی",
        "number_of_unique_products": 130,
        "mean_daily_sales": 89,
        "hygiene_score": 1,
        "created_at": "2017-01-25 02:08:24",
    },
    {
        "id": 86,
        "vendor_id": 86,
        "city_id": 45,
        "address": "آدرس متنی",
        "number_of_unique_products": 111,
        "mean_daily_sales": 88,
        "hygiene_score": 9,
        "created_at": "2020-07-01 04:18:00",
    },
    {
        "id": 89,
        "vendor_id": 89,
        "city_id": 72,
        "address": "آدرس متنی",
        "number_of_unique_products": 141,
        "mean_daily_sales": 96,
        "hygiene_score": 6,
        "created_at": "2019-06-23 07:50:53",
    },
    {
        "id": 93,
        "vendor_id": 93,
        "city_id": 67,
        "address": "آدرس متنی",
        "number_of_unique_products": 44,
        "mean_daily_sales": 21,
        "hygiene_score": 10,
        "created_at": "2020-03-02 05:18:28",
    },
    {
        "id": 95,
        "vendor_id": 95,
        "city_id": 28,
        "address": "آدرس متنی",
        "number_of_unique_products": 141,
        "mean_daily_sales": 66,
        "hygiene_score": 2,
        "created_at": "2020-09-15 02:31:44",
    },
    {
        "id": 100,
        "vendor_id": 100,
        "city_id": 67,
        "address": "آدرس متنی",
        "number_of_unique_products": 103,
        "mean_daily_sales": 100,
        "hygiene_score": 4,
        "created_at": "2021-02-25 05:17:29",
    },
]

vendor_information_evaluations = [
    {
        "id": 1,
        "vendor_information_id": 1,
        "status": "accepted",
        "created_at": "2023-02-11 13:43:10",
        "updated_at": "2023-02-12 10:32:20",
    },
]


vendor_selections = [
    {
        "id": 1,
        "vendor_information_evaluation_id": 1,
        "status": "accepted",
        "created_at": "2023-02-12 13:45:00",
        "updated_at": "2023-02-15 11:25:20",
    },
]

contracts = [
    {
        "id": 1,
        "vendor_id": 1,
        "created_at": "2023-02-20 15:12:00",
    }
]
